=== 19-HRDYTP/JPOS-Project/jpos-2.1.1-SNAPSHOT/cfg/packager/iso8583-binary.dtd
<!ELEMENT isopackager (isofield*)>
        <!ELEMENT isofield EMPTY>
        <!ATTLIST isofield
                id      CDATA #REQUIRED
                length  CDATA #REQUIRED
                name    CDATA #REQUIRED
                class   CDATA #REQUIRED
                >

=== 19-HRDYTP/JPOS-Project/jpos-2.1.1-SNAPSHOT/cfg/packager/ISO8583.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE isopackager SYSTEM "file:///C:/Users/hridh/1new/jpos-2.1.1-SNAPSHOT/cfg/packager/iso8583-binary.dtd">

<isopackager>
    <!-- Define the fields for the ISO 8583 message -->
    <isofield id="0" length="4" name="Message Type Indicator" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="1" length="16" name="Bitmap" class="org.jpos.iso.IFA_BITMAP"/>
    <isofield id="2" length="19" name="Primary Account Number" class="org.jpos.iso.IFA_LLNUM"/>
    <isofield id="3" length="6" name="Processing Code" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="4" length="12" name="Amount, Transaction" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="5" length="12" name="Amount, Settlement" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="6" length="12" name="Amount, Cardholder Billing" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="7" length="10" name="Transmission Date and Time" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="8" length="8" name="Amount, Cardholder Billing Fee" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="9" length="8" name="Conversion Rate, Settlement" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="10" length="6" name="Conversion Rate, Cardholder Billing" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="11" length="6" name="System Trace Audit Number" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="12" length="12" name="Time, Local Transaction" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="13" length="4" name="Date, Local Transaction" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="14" length="4" name="Date, Expiration" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="15" length="4" name="Date, Settlement" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="16" length="4" name="Date, Conversion" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="17" length="4" name="Date, Capture" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="18" length="4" name="Merchant Type" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="19" length="3" name="Acquiring Institution Country Code" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="20" length="3" name="PAN Extended Country Code" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="21" length="3" name="Forwarding Institution Country Code" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="22" length="3" name="Point of Service Entry Mode" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="23" length="3" name="Card Sequence Number" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="24" length="3" name="Function Code" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="25" length="2" name="Point of Service Condition Code" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="26" length="4" name="Point of Service Capture Code" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="27" length="1" name="Authorization Identification Response Length" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="28" length="9" name="Amount, Transaction Fee" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="29" length="9" name="Amount, Settlement Fee" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="30" length="9" name="Amount, Transaction Processing Fee" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="31" length="9" name="Amount, Settlement Processing Fee" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="32" length="11" name="Acquiring Institution Identification Code" class="org.jpos.iso.IFA_LLNUM"/>
    <isofield id="33" length="11" name="Forwarding Institution Identification Code" class="org.jpos.iso.IFA_LLNUM"/>
    <isofield id="34" length="11" name="Primary Account Number, Extended" class="org.jpos.iso.IFA_LLNUM"/>
    <isofield id="35" length="37" name="Track 2 Data" class="org.jpos.iso.IFA_LLCHAR"/>
    <isofield id="36" length="104" name="Track 3 Data" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="37" length="12" name="Retrieval Reference Number" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="38" length="6" name="Authorization Identification Response" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="39" length="2" name="Response Code" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="40" length="3" name="Service Restriction Code" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="41" length="8" name="Card Acceptor Terminal Identification" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="42" length="15" name="Card Acceptor Identification Code" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="43" length="40" name="Card Acceptor Name/Location" class="org.jpos.iso.IFA_LLCHAR"/>
    <isofield id="44" length="25" name="Additional Response Data" class="org.jpos.iso.IFA_LLCHAR"/>
    <isofield id="45" length="76" name="Track 1 Data" class="org.jpos.iso.IFA_LLCHAR"/>
    <isofield id="46" length="999" name="Additional Data - ISO" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="47" length="999" name="Additional Data - National" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="48" length="999" name="Additional Data - Private" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="49" length="3" name="Currency Code, Transaction" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="50" length="3" name="Currency Code, Settlement" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="51" length="3" name="Currency Code, Cardholder Billing" class="org.jpos.iso.IFA_NUMERIC"/>
    <isofield id="52" length="16" name="Personal Identification Number (PIN) Data" class="org.jpos.iso.IFA_BINARY"/>
    <isofield id="53" length="16" name="Security Related Control Information" class="org.jpos.iso.IFA_BINARY"/>
    <isofield id="54" length="120" name="Additional Amounts" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="55" length="999" name="Reserved ISO" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="56" length="999" name="Reserved ISO" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="57" length="999" name="Reserved National" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="58" length="999" name="Reserved National" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="59" length="999" name="Reserved Private" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="60" length="999" name="Reserved Private" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="61" length="999" name="Reserved Private" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="62" length="999" name="Reserved Private" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="63" length="999" name="Reserved Private" class="org.jpos.iso.IFA_LLLCHAR"/>
    <isofield id="64" length="16" name="Message Authentication Code (MAC)" class="org.jpos.iso.IFA_BINARY"/>
</isopackager>
